name   名字: NodeJS with Webpack

on   在:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs   工作:   工作:
  build:
    runs-on   上运行:ubuntu-latest   运行在: ubuntu-latest

    strategy   策略:   策略:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps   步骤:   步骤:
    - —用途：actions/checkout@v4uses: actions/checkout@v4

    - name   名字: Use Node.js ${{ matrix.node-version }}
      uses   使用: actions/setup-node@v4
      with   :   与:
        node-version: ${{ matrix.node-version }}

    - name   名字: Build
      run   运行:|   运行: |
        npm install
        npx webpack
